//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphicapplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class _9_ : global::System.Configuration.ApplicationSettingsBase {
        
        private static _9_ defaultInstance = ((_9_)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new _9_())));
        
        public static _9_ Default {
            get {
                return defaultInstance;
            }
        }
    }
}
